export const SET_LOCATION_PERMISSION = 'permission/SET_LOCATION_PERMISSION';
export const GET_LOCATION_PERMISSION = 'permission/GET_LOCATION_PERMISSION';
export const ASK_LOCATION_PERMISSION = 'permission/ASK_LOCATION_PERMISSION';

export const DENY_LOCATION_PERMISSION = 'permission/DENY_LOCATION_PERMISSION';
export const ACCEPT_LOCATION_PERMISSION =
  'permission/ACCEPT_LOCATION_PERMISSION';
