require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'baniking_mobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"

  target 'baniking_mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  use_flipper!({ 'Flipper' => '0.74.0' }) # added by Daria
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'baniking_mobile-tvOS' do
  # Pods for baniking_mobile-tvOS

  target 'baniking_mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
