export { default as TotalPointScores } from './images/svg/total-point-scores.svg';
export { default as MenuHumberger } from './images/svg/menu-hamburger.svg';
export { default as MenuLogo } from './images/svg/menu-logo.svg';
export { default as Notify } from './images/svg/notify.svg';
export { default as CloseMenu } from './images/svg/close-menu.svg';
export { default as AuthLogo } from './images/svg/auth-logo.svg';
export { default as AuthLogoLeft } from './images/svg/auth-logo-left.svg';
export { default as AuthLogoRight } from './images/svg/auth-logo-right.svg';
export { default as TextLabelNecessary } from './images/svg/text-label-necessary.svg';
